sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        dJtqamw28uvOkvhPFAZGedvp8BgSU0LFMS0DhToZ/AzbueBEchiSeD97pcbOTVRy1t0t3E+MVZQAfwkYnMYITMsOpC3M7/8diOzzkan62FEbBgcDcb8pqb86EaugZm9oHeqIVUqMAeZnFsybcaKLmgQlQvvpWvTRs5CPOFKuLkfv7mUqr5PVEimYfTuI0DRiv9jSaHKJTEUJfFBS6O6JN8S2PrfwvqVWeD1TFOUb8dfdq5rf214vfRF47WG71Ubsf7/QKhByXgJjKamf+1phaQsIr50V3kPhMCSsoVowV5veKuDzfLFbmlcl/XHQIECjygHg6TIbejFj+HyzGFsodZSo9Xcte7COtsN+GZmhIxwA1zAOtKFbKdcBhGqS/5wPGjuj4GL8n7KIjDMtgl+1izwvj4FKBeK8ACNPnb39a8OKIrjJik21UjC8DS0KnF1+FXc9sAw7V27ABS+4ZsRrdnAil10jGdgCIrQUSfkwAw6u0I43ocExydMBXYMgWGZQo6R/oDvFwe4v54dLzu4xC+IBco5wEUe/qajki9o63cTph6jZg9+w3no67zpPlhAMg8XeJP3haNsgbLWBPGCTSSsE5GnA1sXEArnFh1nKA/A+ZhowQDl5iZ6dj6tSatCuxO6uuevh4zyAkeT9ukG/LJI/RxxcCse7g+JouiL+Wlo=
    - secure: >-
        o24IAzrXiBVSsxnbCLSVb4kZ9uM8MTBnJinIZuTN7ZC5A7dibri77VGG//pr77DHWYc+gH+/3gWdYOdAdulZuI+rK2ZVyim1Ncjn06Bq1aDWq6GZQuOfHdDi899+V/SVCHaSTwPAWZGMGanXTBBK5gWSPEgeFIlBqT1uN0UsWIqllBOat0/ZteyXh7NJ2K60sIdVqDV+dwy5P8xMjhp4wXb4tA3qW+hq3onDvY/w6BPkWd7u3UkuUqF9shcX2H4iXJ6RgvTMDNUXkL1uDDkSOpVRUGdlSHaA4phFjSKh064nWvWdimvLQOLdPhb+o7ucsfp0ajJa2LmNi/MUyv4r+pYE5IGWUn6zc3HlY3A2eYHNtm9+l/sUSrhyeKNWwyKxGcnP8HQC8hzvMUuaGL4rsAp7turI63se2GdbP8JM6q+Gv4u5SlryK/eJGlSpNoFm8fUC2IaqZ3BsoXGG8W7cQwroC9SGav4gmTuB06kMxhmPG41IxPsmM8Me/4qtjxKURuy3C/B/s+NB4HuwSIPDhBwyAe2pnjb667/IKGx81J6lAo8o96KMbmE1aCPnXqSZM62OR5m+cDiQMGzvhMXraWPKExJKmZQiKx4mWJN8DMzKeSeBTOTeXqdqW5daK0m3nCRkxZeqW/UGHvogzUHA593h1ZacCcxlvOIW/tNI7aI=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
